-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS "COFFEE".sales_transaction
(
    transaction_id integer NOT NULL,
    transaction_date date,
    transaction_time timestamp without time zone[],
    sales_outlet_id integer,
    staff_id integer,
    customer_id integer,
    PRIMARY KEY (transaction_id)
);

CREATE TABLE IF NOT EXISTS "COFFEE".product_type
(
    product_type_id integer NOT NULL,
    product_category character varying,
    product_type character varying,
    PRIMARY KEY (product_type_id)
);

CREATE TABLE IF NOT EXISTS "COFFEE".product
(
    product_id integer NOT NULL,
    product_type_id integer,
    product_name "char",
    description text,
    price double precision,
    PRIMARY KEY (product_id)
);

CREATE TABLE IF NOT EXISTS "COFFEE".transaction_details
(
    transaction_id integer NOT NULL,
    product_id integer NOT NULL,
    quantity double precision,
    price numeric,
    PRIMARY KEY (transaction_id, product_id)
);
END;