-- Creacion de la base de datos
CREATE SCHEMA IF NOT EXISTS empresa;

USE empresa;

CREATE TABLE Tb_clientes(
DNI VARCHAR(11) NOT NULL,
NOMBRE VARCHAR(100) NULL,
DIRECCION VARCHAR(150),
BARRIO VARCHAR(50),
CIUDAD VARCHAR(50),
ESTADO VARCHAR(10),
CP VARCHAR(10),
FECHA_NACIMIENTO DATE,
EDAD SMALLINT,
SEXO VARCHAR(1),
LIMITE_CREDITO FLOAT,
VOLUMEN_COMPRA FLOAT,
PRIMERA_COMPRA BIT,
PRIMARY KEY (DNI)
);

CREATE TABLE Tb_vendedor(
MATRICULA_PK VARCHAR(5) NOT NULL,
NOMBRE VARCHAR(100),
BARRIO VARCHAR(50),
COMISION FLOAT,
FECHA_ADMISION DATE,
VACACIONES BIT(1),
PRIMARY KEY (MATRICULA_PK)
);

CREATE TABLE Tb_Productos(
CODIGO_PK VARCHAR(10) NOT NULL,
DESCRIPCION VARCHAR(100),
SABOR VARCHAR(50),
TAMANO VARCHAR(50),
ENVASE VARCHAR(50),
PRECIO_LISTA FLOAT,
PRIMARY KEY (CODIGO_PK)
);


-- Modificaciones sobre la tabla
ALTER TABLE empresa.tb_vendedor RENAME empresa.tb_Vendedor;

CREATE TABLE  tb_venta(
NUMERO VARCHAR(5) NOT NULL,
FECHA DATE,
DNI VARCHAR(11) NOT NULL,
MATRICULA VARCHAR(5) NOT NULL,
IMPUESTO FLOAT,
PRIMARY KEY(NUMERO),
FOREIGN KEY (DNI) REFERENCES tb_clientes(DNI),
FOREIGN KEY (MATRICULA) REFERENCES tb_vendedor(MATRICULA_PK)
);

DROP TABLE tb_Items_Vendidos;

CREATE TABLE tb_Items_Vendidos(
NUMERO VARCHAR(5) NOT NULL,
CODIGO VARCHAR(10) NOT NULL,
CANTIDAD INT,
PRECIO FLOAT,
PRIMARY KEY(NUMERO, CODIGO),
FOREIGN KEY(NUMERO) REFERENCES tb_venta(NUMERO),
FOREIGN KEY(CODIGO) REFERENCES tb_productos(CODIGO_PK)
);


-- Ejemplo de insercion de datos dentro de una tabla
INSERT INTO tb_clientes VALUES (
'3623344710', 'Marcos Rosas', 'Av. Universidad', 'Del Valle', 'Ciudad de Mexico', 'EM', '22002012', '1995-01-13', 26, 'M', 1100000, 220000, 1
);