CREATE TABLE IF NOT EXISTS tb_facturacion(
FECHA DATE NULL,
VENTA_TOTAL FLOAT
);

DELIMITER //
CREATE  PROCEDURE `sp_triggers`()
BEGIN
	DELETE FROM tb_facturacion;
    INSERT INTO tb_facturacion 
    SELECT A.FECHA, SUM(B.CANTIDAD * B.PRECIO) AS VENTA_TOTAL
    FROM tb_venta A INNER JOIN tb_items_vendidos
    ON A.NUMERO = B.NUMERO
    GROUP BY A.FECHA;
END //



DELIMITER //
CREATE TRIGGER TG_FACTURACION_INSERT
AFTER INSERT ON tb_items_vendidos
FOR EACH ROW BEGIN
	CALL sp_triggers;
END //

DELIMITER //
CREATE TRIGGER TG_FACTURACION_DELETE
AFTER DELETE ON tb_items_vendidos
FOR EACH ROW BEGIN
  CALL sp_triggers;
END //

DELIMITER //
CREATE TRIGGER TG_FACTURACION_UPDATE
AFTER UPDATE ON tb_items_vendidos
FOR EACH ROW BEGIN
	CALL sp_triggers;
END //

SELECT * FROM tb_facturacion WHERE FECHA = "20220812";