-- SUBCONSULTAS, UTILIZADAS PARA EXTRAER DATOS CONDICIONADOS DENTRO DE UNA CONSULTA Y PASARLOS A OTRA CONSULTA PRINCIPAL
-- LA ESTRUCTURA GENERAL ES LA SIGUINTE
-- SELECT X, Y FROM tb1 WHERE Y IN (SELECT Y FROM tb2 WHERE z  = 'x')

SELECT * FROM tabla_de_clientes WHERE BARRIO IN (
 SELECT DISTINCT BARRIO FROM tabla_de_vendedores
);

SELECT X.ENVASE, X.PRECIO_MAXIMO FROM (SELECT ENVASE, MAX(PRECIO_DE_LISTA) AS PRECIO_MAXIMO FROM tabla_de_productos
GROUP BY ENVASE) X 
WHERE X.PRECIO_MAXIMO >= 10;

SELECT ENVASE, MAX(PRECIO_DE_LISTA) AS PRECIO_MAXIMO FROM tabla_de_productos
GROUP BY ENVASE;

-- INFORME DE CLIENTES INVALIDOAS, LISTAR A  LAS VENTAN INVALIDAS Y CALCULAR LA DIFERENCIA
-- ENTRE EL LIMITE DE VENTA MAXIMO Y LA CANTIDAD VENDIDA EN PORCENTAJE

-- CONSULTADE LA CANTIDAD VENDIDA POR VENDADOR Y CAPACIDAD MAXIMA DE COMPRA POR CLIENTE
SELECT A.DNI,
	   A.NOMBRE, 
       A.FECHA, 
       A.CANTIDAD_VENDIDA - A.CANTIDAD_MAXIMA AS DIFERENCIA,
       CASE
			WHEN A.CANTIDAD_VENDIDA - A.CANTIDAD_MAXIMA <= 0 THEN 'VENTA_VALIDA'  -- Case no reconoce el alias anterior
			ELSE 'VENTA_INVALIDA'
       END AS STATUS_VENTA,
       ROUND((1 - (A.CANTIDAD_MAXIMA/A.CANTIDAD_VENDIDA)) * 100, 2) AS PORCENTAJE
       FROM(
       -- CONSULTA PARA CALCULAR LAS CANTIDADES DE VENTAS
		SELECT  F.DNI, 
				TC.NOMBRE,
				DATE_FORMAT(F.FECHA_VENTA, "%m-%Y") AS FECHA , 
				SUM(IFA.CANTIDAD) AS CANTIDAD_VENDIDA,
				MAX(TC.VOLUMEN_DE_COMPRA)/10 AS CANTIDAD_MAXIMA -- Se divide entre 10 para que la cantidad de compra sea en decimales
                -- de decilitros a litros
		FROM facturas F INNER JOIN items_facturas IFA ON F.NUMERO = IFA.NUMERO
						INNER JOIN tabla_de_clientes TC ON TC.DNI = F.DNI
		GROUP BY F.DNI, FECHA) A;



        -- REPORTE DE VENTA A CLIENTE, CANTIDAD VENDIDA Y CANTIDAD MAXIMA
SELECT TC.NOMBRE, 
		F.DNI, 
		DATE_FORMAT(F.FECHA_VENTA, "%m-%Y") AS FECHA , 
        SUM(IFA.CANTIDAD) AS CANTIDAD_VENDIDA,
        MAX(TC.VOLUMEN_DE_COMPRA)/10 AS CANTIDAD_MAXIMA 
FROM facturas F INNER JOIN items_facturas IFA ON F.NUMERO = IFA.NUMERO
				INNER JOIN tabla_de_clientes TC ON  F.DNI = TC.DNI 
GROUP BY F.DNI, FECHA, TC.NOMBRE; 

-- EVALUACION DE QUE LA VENTA HECHA ES VALIDA O INVALIDA
SELECT A.DNI, 
		A.NOMBRE, 
		A.FECHA,
        -- A.CANTIDAD_VENDIDA - A.CANTIDAD_MAXIMA AS DIFERENCIA,
        CASE
			WHEN  A.CANTIDAD_VENDIDA - A.CANTIDAD_MAXIMA < 0 THEN 'VENTA_INVALIDA'
            ELSE 'VENTA VALIDA'
		END AS ESTADO
        FROM(
        SELECT TC.NOMBRE, 
		F.DNI, 
		DATE_FORMAT(F.FECHA_VENTA, "%m-%Y") AS FECHA , 
        SUM(IFA.CANTIDAD) AS CANTIDAD_VENDIDA,
        MAX(TC.VOLUMEN_DE_COMPRA)/10 AS CANTIDAD_MAXIMA 
		FROM facturas F INNER JOIN items_facturas IFA ON F.NUMERO = IFA.NUMERO
				INNER JOIN tabla_de_clientes TC ON  F.DNI = TC.DNI 
		GROUP BY F.DNI, FECHA, TC.NOMBRE 
        ) A;