-- SUBCONSULTAS, UTILIZADAS PARA EXTRAER DATOS CONDICIONADOS DENTRO DE UNA CONSULTA Y PASARLOS A OTRA CONSULTA PRINCIPAL
-- LA ESTRUCTURA GENERAL ES LA SIGUINTE
-- SELECT X, Y FROM tb1 WHERE Y IN (SELECT Y FROM tb2 WHERE z  = 'x')

SELECT * FROM tabla_de_clientes WHERE BARRIO IN (
 SELECT DISTINCT BARRIO FROM tabla_de_vendedores
);

SELECT X.ENVASE, X.PRECIO_MAXIMO FROM (SELECT ENVASE, MAX(PRECIO_DE_LISTA) AS PRECIO_MAXIMO FROM tabla_de_productos
GROUP BY ENVASE) X 
WHERE X.PRECIO_MAXIMO >= 10;

SELECT ENVASE, MAX(PRECIO_DE_LISTA) AS PRECIO_MAXIMO FROM tabla_de_productos
GROUP BY ENVASE;