-- SUBCONSULTAS, UTILIZADAS PARA EXTRAER DATOS CONDICIONADOS DENTRO DE UNA CONSULTA Y PASARLOS A OTRA CONSULTA PRINCIPAL
-- LA ESTRUCTURA GENERAL ES LA SIGUINTE
-- SELECT X, Y FROM tb1 WHERE Y IN (SELECT Y FROM tb2 WHERE z  = 'x')

SELECT * FROM tabla_de_clientes WHERE BARRIO IN (
 SELECT DISTINCT BARRIO FROM tabla_de_vendedores
);

SELECT X.ENVASE, X.PRECIO_MAXIMO FROM (SELECT ENVASE, MAX(PRECIO_DE_LISTA) AS PRECIO_MAXIMO FROM tabla_de_productos
GROUP BY ENVASE) X 
WHERE X.PRECIO_MAXIMO >= 10;

SELECT ENVASE, MAX(PRECIO_DE_LISTA) AS PRECIO_MAXIMO FROM tabla_de_productos
GROUP BY ENVASE;

-- INFORME DE CLIENTES INVALIDOAS, LISTAR A  LAS VENTAN INVALIDAS Y CALCULAR LA DIFERENCIA
-- ENTRE EL LIMITE DE VENTA MAXIMO Y LA CANTIDAD VENDIDA EN PORCENTAJE

-- CONSULTADE LA CANTIDAD VENDIDA POR VENDADOR Y CAPACIDAD MAXIMA DE COMPRA POR CLIENTE
SELECT A.DNI,
	   A.NOMBRE, 
       A.FECHA, 
       A.CANTIDAD_VENDIDA - A.CANTIDAD_MAXIMA AS DIFERENCIA,
       CASE
			WHEN A.CANTIDAD_VENDIDA - A.CANTIDAD_MAXIMA <= 0 THEN 'VENTA_VALIDA'  -- Case no reconoce el alias anterior
			ELSE 'VENTA_INVALIDA'
       END AS STATUS_VENTA,
       ROUND((1 - (A.CANTIDAD_MAXIMA/A.CANTIDAD_VENDIDA)) * 100, 2) AS PORCENTAJE
       FROM(
       -- CONSULTA PARA CALCULAR LAS CANTIDADES DE VENTAS
		SELECT  F.DNI, 
				TC.NOMBRE,
				DATE_FORMAT(F.FECHA_VENTA, "%m-%Y") AS FECHA , 
				SUM(IFA.CANTIDAD) AS CANTIDAD_VENDIDA,
				MAX(TC.VOLUMEN_DE_COMPRA)/10 AS CANTIDAD_MAXIMA -- Se divide entre 10 para que la cantidad de compra sea en decimales
                -- de decilitros a litros
		FROM facturas F INNER JOIN items_facturas IFA ON F.NUMERO = IFA.NUMERO
						INNER JOIN tabla_de_clientes TC ON TC.DNI = F.DNI
		GROUP BY F.DNI, FECHA) A;



        -- REPORTE DE VENTA A CLIENTE, CANTIDAD VENDIDA Y CANTIDAD MAXIMA
SELECT TC.NOMBRE, 
		F.DNI, 
		DATE_FORMAT(F.FECHA_VENTA, "%m-%Y") AS FECHA , 
        SUM(IFA.CANTIDAD) AS CANTIDAD_VENDIDA,
        MAX(TC.VOLUMEN_DE_COMPRA)/10 AS CANTIDAD_MAXIMA 
FROM facturas F INNER JOIN items_facturas IFA ON F.NUMERO = IFA.NUMERO
				INNER JOIN tabla_de_clientes TC ON  F.DNI = TC.DNI 
GROUP BY F.DNI, FECHA, TC.NOMBRE; 

-- EVALUACION DE QUE LA VENTA HECHA ES VALIDA O INVALIDA
SELECT A.DNI, 
		A.NOMBRE, 
		A.FECHA,
        -- A.CANTIDAD_VENDIDA - A.CANTIDAD_MAXIMA AS DIFERENCIA,
        CASE
			WHEN  A.CANTIDAD_VENDIDA - A.CANTIDAD_MAXIMA < 0 THEN 'VENTA_INVALIDA'
            ELSE 'VENTA VALIDA'
		END AS ESTADO
        FROM(
        SELECT TC.NOMBRE, 
		F.DNI, 
		DATE_FORMAT(F.FECHA_VENTA, "%m-%Y") AS FECHA , 
        SUM(IFA.CANTIDAD) AS CANTIDAD_VENDIDA,
        MAX(TC.VOLUMEN_DE_COMPRA)/10 AS CANTIDAD_MAXIMA 
		FROM facturas F INNER JOIN items_facturas IFA ON F.NUMERO = IFA.NUMERO
				INNER JOIN tabla_de_clientes TC ON  F.DNI = TC.DNI 
		GROUP BY F.DNI, FECHA, TC.NOMBRE 
        ) A;


-- Al tener una consulta tan compleja como la anterior se puede utilizar una 
--view para no tener que repetir la consulta
USE `jugos_ventas`;
CREATE  OR REPLACE VIEW `vw_ventas_clientes` AS
SELECT A.DNI, 
		A.NOMBRE, 
		A.FECHA,
        -- A.CANTIDAD_VENDIDA - A.CANTIDAD_MAXIMA AS DIFERENCIA,
        CASE
			WHEN  A.CANTIDAD_VENDIDA - A.CANTIDAD_MAXIMA < 0 THEN 'VENTA_INVALIDA'
            ELSE 'VENTA VALIDA'
		END AS ESTADO
        FROM(
        SELECT TC.NOMBRE, 
		F.DNI, 
		DATE_FORMAT(F.FECHA_VENTA, "%m-%Y") AS FECHA , 
        SUM(IFA.CANTIDAD) AS CANTIDAD_VENDIDA,
        MAX(TC.VOLUMEN_DE_COMPRA)/10 AS CANTIDAD_MAXIMA 
		FROM facturas F INNER JOIN items_facturas IFA ON F.NUMERO = IFA.NUMERO
				INNER JOIN tabla_de_clientes TC ON  F.DNI = TC.DNI 
		GROUP BY F.DNI, FECHA, TC.NOMBRE 
        ) A;;
        /*
        INFORME DE CLIENTES DE VENTAS INVALIDAS, TENIENDO LAS
        VENTAS INVALIDAS DEL 2018 EXCENDIENTO EL 50% DE SU CAPACIDAD POR MES
        */

        SELECT DNI, NOMBRE, FECHA,ESTADO, SUM(DIFERENCIA) FROM vw_ventas_clientes
WHERE (SUBSTRING(FECHA,4,4) = '2018') AND ESTADO = 'VENTA_INVALIDA'
GROUP BY DNI, NOMBRE,FECHA, ESTADO;

SELECT A.DNI, A.NOMBRE, A.MES_AÑO, 
A.CANTIDAD_VENDIDA - A.CANTIDAD_MAXIMA AS DIFERENCIA,
CASE
   WHEN  (A.CANTIDAD_VENDIDA - A.CANTIDAD_MAXIMA) <= 0 THEN 'Venta Válida'
   ELSE 'Venta Inválida'
END AS STATUS_VENTA, ROUND((1 - (A.CANTIDAD_MAXIMA/A.CANTIDAD_VENDIDA)) * 100,2) AS PORCENTAJE
 FROM(
SELECT F.DNI, TC.NOMBRE, DATE_FORMAT(F.FECHA_VENTA, "%m - %Y") AS MES_AÑO, 
SUM(IFa.CANTIDAD) AS CANTIDAD_VENDIDA, 
MAX(VOLUMEN_DE_COMPRA)/10 AS CANTIDAD_MAXIMA  
FROM facturas F 
INNER JOIN 
items_facturas IFa
ON F.NUMERO = IFa.NUMERO
INNER JOIN 
tabla_de_clientes TC
ON TC.DNI = F.DNI
GROUP BY
F.DNI, TC.NOMBRE, DATE_FORMAT(F.FECHA_VENTA, "%m - %Y"))A
WHERE (A.CANTIDAD_MAXIMA - A.CANTIDAD_VENDIDA) < 0 AND ROUND((1 - (A.CANTIDAD_MAXIMA/A.CANTIDAD_VENDIDA)) * 100,2) > 50
AND A.MES_AÑO LIKE "%2018";

-----------------------------------------------------------
-- CANTIDAD VENDIDA POR SABOR EN EL ANNO 2O16
SELECT P.SABOR,
       SUM(IFA.CANTIDAD) AS CANTIDAD_TOTAL,
	   YEAR(F.FECHA_VENTA) AS ANNO
FROM tabla_de_productos P 
INNER JOIN items_facturas IFA ON P.CODIGO_DEL_PRODUCTO = IFA.CODIGO_DEL_PRODUCTO
INNER JOIN facturas F ON F.NUMERO = IFA.NUMERO
WHERE  YEAR(F.FECHA_VENTA) = '2016'
GROUP BY P.SABOR, ANNO
ORDER BY SUM(IFA.CANTIDAD) DESC; 

--  VENTA DE PRODUCTOS POR PORCENTAJE
SELECT VENTAS_SABOR.SABOR, 
	   VENTAS_TOTAL.CANTIDAD_TOTAL,
       VENTAS_SABOR.ANNO,
       (ROUND((VENTAS_SABOR.CANTIDAD_TOTAL/VENTAS_TOTAL.CANTIDAD_TOTAL)*100,2)) AS PORCENTAJE
       FROM(
SELECT P.SABOR,
       SUM(IFA.CANTIDAD) AS CANTIDAD_TOTAL,
	   YEAR(F.FECHA_VENTA) AS ANNO
FROM tabla_de_productos P 
INNER JOIN items_facturas IFA ON P.CODIGO_DEL_PRODUCTO = IFA.CODIGO_DEL_PRODUCTO
INNER JOIN facturas F ON F.NUMERO = IFA.NUMERO
WHERE  YEAR(F.FECHA_VENTA) = '2016'
GROUP BY P.SABOR, ANNO
ORDER BY SUM(IFA.CANTIDAD) DESC) VENTAS_SABOR INNER JOIN  
-- VENTA POR ANNO
(SELECT 
       SUM(IFA.CANTIDAD) AS CANTIDAD_TOTAL,
	   YEAR(F.FECHA_VENTA) AS ANNO
FROM tabla_de_productos P 
INNER JOIN items_facturas IFA ON P.CODIGO_DEL_PRODUCTO = IFA.CODIGO_DEL_PRODUCTO
INNER JOIN facturas F ON F.NUMERO = IFA.NUMERO
WHERE  YEAR(F.FECHA_VENTA) = '2016'
GROUP BY  ANNO
ORDER BY SUM(IFA.CANTIDAD) DESC) VENTAS_TOTAL 
ON VENTAS_SABOR.ANNO = VENTAS_TOTAL.ANNO; 

--RANKING DE VENTA DE PRODUCTOS POR TAMANO DE PRODUCTO:
--  VENTA DE PRODUCTOS POR PORCENTAJE
SELECT VENTAS_TAMANO.TAMANO, 
	   VENTAS_TOTAL.CANTIDAD_TOTAL,
       VENTAS_TAMANO.ANNO,
       (ROUND((VENTAS_TAMANO.CANTIDAD_TOTAL/VENTAS_TOTAL.CANTIDAD_TOTAL)*100,2)) AS PORCENTAJE
       FROM(
SELECT P.TAMANO,
       SUM(IFA.CANTIDAD) AS CANTIDAD_TOTAL,
	   YEAR(F.FECHA_VENTA) AS ANNO
FROM tabla_de_productos P 
INNER JOIN items_facturas IFA ON P.CODIGO_DEL_PRODUCTO = IFA.CODIGO_DEL_PRODUCTO
INNER JOIN facturas F ON F.NUMERO = IFA.NUMERO
WHERE  YEAR(F.FECHA_VENTA) = '2016'
GROUP BY P.TAMANO, ANNO
ORDER BY SUM(IFA.CANTIDAD) DESC) VENTAS_TAMANO INNER JOIN  
-- VENTA POR ANNO
(SELECT 
       SUM(IFA.CANTIDAD) AS CANTIDAD_TOTAL,
	   YEAR(F.FECHA_VENTA) AS ANNO
FROM tabla_de_productos P 
INNER JOIN items_facturas IFA ON P.CODIGO_DEL_PRODUCTO = IFA.CODIGO_DEL_PRODUCTO
INNER JOIN facturas F ON F.NUMERO = IFA.NUMERO
WHERE  YEAR(F.FECHA_VENTA) = '2016'
GROUP BY  ANNO
ORDER BY SUM(IFA.CANTIDAD) DESC) VENTAS_TOTAL 

ON VENTAS_TAMANO.ANNO = VENTAS_TOTAL.ANNO
ORDER BY PORCENTAJE DESC
LIMIT 5; 