-- FUNCIONES PRECONSTRUIDAS DE MYSQL --
SELECT LTRIM("	MySQL es facil") AS RESULTADO;
SELECT RTRIM("     MySQL es facil  ") AS RESULTADO;
SELECT TRIM("  MYSQL   ") AS RESULTADO;
SELECT CONCAT("MYSQL ES", "MY NEW SKILL") AS RESULTADO;
SELECT UPPER("Expresion principal") AS RESULTADO;
SELECT LOWER("HOLA A TODOS") AS RESULTADO;
SELECT SUBSTR("Este es un texto largo", 12, 4) AS SELECTIONADO;
SELECT CONCAT(NOMBRE, ", DNI: ", DNI) FROM tabla_de_clientes;

USE jugos_ventas;
SELECT NOMBRE, CONCAT(DIRECCION_1,' ', BARRIO,' ', CIUDAD,' ', ESTADO) AS DIRECCION_COMPLETA 
FROM tabla_de_clientes ;

-- FUNCIONES DE FECHA --
SELECT ADDDATE("2017-06-15" , INTERVAL 10 DAY) AS NUEVA_FECHA;  -- AGREGA 10 DIAS A LA FECHA INGRESADA
SELECT CURDATE();
SELECT DATEDIFF("2017-06-25","2017-06-15");

SELECT DAY("2017-06-15");
SELECT DAYOFWEEK("2017-06-15") AS DIA_SEMANA;
SELECT LOCALTIMESTAMP();

SELECT MONTHNAME(CURRENT_TIMESTAMP());
SELECT DAYNAME(CURRENT_TIMESTAMP());
SELECT DATEDIFF(CURRENT_TIMESTAMP(), "2021-01-01") AS DIFERENCIA_DE_DIAS;

SELECT DISTINCT FECHA_VENTA,
DAYNAME(FECHA_VENTA) AS DIA, MONTHNAME(FECHA_VENTA) AS MES, YEAR(FECHA_VENTA) AS ANO FROM facturas;

-- Extracicon de dias de una fecha
SELECT DATE_SUB("2017-06-15", INTERVAL 10 DAY) AS Resultado;


SELECT NOMBRE,  TIMESTAMPDIFF(YEAR, FECHA_DE_NACIMIENTO, CURDATE()) AS EDAD
FROM tabla_de_clientes;  -- Extrae la diferencia de fechas por ano

SELECT(34 + 346 - 67)/ 15 * 29 AS RESULTADO;
SELECT CEILING (23.1222);
SELECT FLOOR (23.9999);
SELECT RAND() AS RESULTADO;

SELECT NUMERO, CANTIDAD, PRECIO, 
ROUND(CANTIDAD * PRECIO) AS FACTURACION FROM items_facturas;

SELECT F.DNI, FLOOR(SUM((F.IMPUESTO * (IFA.CANTIDAD * IFA.PRECIO))))  AS FACTURA, YEAR(FECHA_VENTA) AS ANNO
FROM  facturas F INNER JOIN items_facturas IFA ON F.NUMERO = IFA.NUMERO
WHERE YEAR(FECHA_VENTA) = 2016
GROUP BY ANNO, F.DNI, F.IMPUESTO;

SELECT CONCAT("LA FECHA ACTUAL ES: ", CURRENT_TIMESTAMP()) AS FECHA_ACTUAL;

-- FORMATO DE TEXTO DE FECHAS A CADENAS DE TEXTO --
SELECT DATE_FORMAT(CURRENT_TIMESTAMP(), "%w, %d/%m/%Y a las %T") AS RESULTADO;

-- CASTEO DE DATOS
SELECT CONVERT(23.45, CHAR) AS RESULTADO;
SELECT SUBSTRING(CONVERT(23.45, CHAR),3,1) AS RESULTADO;

SELECT F.DNI, FLOOR(SUM((F.IMPUESTO * (IFA.CANTIDAD * IFA.PRECIO))))  AS FACTURA, YEAR(FECHA_VENTA) AS ANNO
FROM  facturas F INNER JOIN items_facturas IFA ON F.NUMERO = IFA.NUMERO
WHERE YEAR(FECHA_VENTA) = 2016
GROUP BY ANNO, F.DNI, F.IMPUESTO;

SELECT CONCAT('El cliente ', TC.NOMBRE, ' facturo ', CONVERT(FLOOR(SUM(IFA.CANTIDAD* IFA.PRECIO)), CHAR(20)), 
	   ' en el ano ', CONVERT(YEAR(F.FECHA_VENTA), CHAR(20))) AS FRASE 
FROM facturas F
INNER JOIN items_facturas IFA ON  IFA.NUMERO = F.NUMERO
INNER JOIN tabla_de_clientes TC ON F.DNI = TC.DNI
WHERE YEAR(FECHA_VENTA) = 2016
GROUP BY TC.NOMBRE, F.FECHA_VENTA;

-- GROUP BY TC.NOMBRE, YEAR(FECHA_VENTA);
SELECT CONCAT('El cliente ', TC.NOMBRE, ' facturó ', 
CONVERT(SUM(IFa.CANTIDAD * IFa.precio), CHAR(20))
 , ' en el año ', CONVERT(YEAR(F.FECHA_VENTA), CHAR(20))) AS FRASE FROM facturas F
INNER JOIN items_facturas IFa ON F.NUMERO = IFa.NUMERO
INNER JOIN tabla_de_clientes TC ON F.DNI = TC.DNI
WHERE YEAR(FECHA_VENTA) = 2016;
