-- TABLA LOGICA QUE RESULTA DE UNA CONSULTA QUE SE PUEDE USAR POSTERIORMENTE PARA MAS CONSULTAS
-- ESTRUCTURA BASICA
-- CREATE OR REPLAE VIEW `vw_envases_grandes` AS SELECT ENVASE, AX(PRECIO_DE_LISTA) AS PRECIO_MAXIMO FROM tabla_de_productos GROUP BY ENVASE;;

SELECT X.ENVASE, X.PRECIO_MAXIMO FROM 
(	SELECT ENVASE, MAX(PRECIO_DE_LISTA)
	AS PRECIO_MAXIMO FROM tabla_de_productos GROUP BY ENVASE);
    
SELECT X.ENVASE, X.PRECIO_MAXIMO FROM
vw_envases_grandes X WHERE PRECIO_MAXIMO >= 10;

SELECT A.ENVASE, A.ENVASE, A.PRECIO_DE_LISTA, B.PRECIO_MAXIMO  FROM tabla_de_productos A
INNER JOIN vw_envases_grandes B ON A.ENVASE = B.ENVASE; -- Se puede ver el precio maximo por producto

SELECT A.ENVASE, A.ENVASE, A.PRECIO_DE_LISTA, 
ROUND(((A.PRECIO_DE_LISTA/B.PRECIO_MAXIMO)-1)*100,2) AS Porcentaje_variacion  -- Porcentaje  de variacion
FROM tabla_de_productos A
INNER JOIN vw_envases_grandes B ON A.ENVASE = B.ENVASE;